/*
* generated by Xtext
*/
package org.xtext.featuremodel.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.featuremodel.services.FeatureModelGrammarAccess;

public class FeatureModelParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private FeatureModelGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.featuremodel.parser.antlr.internal.InternalFeatureModelParser createParser(XtextTokenStream stream) {
		return new org.xtext.featuremodel.parser.antlr.internal.InternalFeatureModelParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "FeatureModel";
	}
	
	public FeatureModelGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(FeatureModelGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
