/*
* generated by Xtext
*/
package org.xtext.plaovgraph.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.xtext.plaovgraph.services.PLAOVgraphGrammarAccess;

public class PLAOVgraphParser extends AbstractContentAssistParser {
	
	@Inject
	private PLAOVgraphGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.xtext.plaovgraph.ui.contentassist.antlr.internal.InternalPLAOVgraphParser createParser() {
		org.xtext.plaovgraph.ui.contentassist.antlr.internal.InternalPLAOVgraphParser result = new org.xtext.plaovgraph.ui.contentassist.antlr.internal.InternalPLAOVgraphParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getGoal_ModelAccess().getAlternatives(), "rule__Goal_Model__Alternatives");
					put(grammarAccess.getRelationshipAccess().getAlternatives(), "rule__Relationship__Alternatives");
					put(grammarAccess.getPropertyAccess().getAlternatives(), "rule__Property__Alternatives");
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getElementTypesAccess().getAlternatives(), "rule__ElementTypes__Alternatives");
					put(grammarAccess.getDecompositionCategoryAccess().getAlternatives(), "rule__DecompositionCategory__Alternatives");
					put(grammarAccess.getCorrelationCategoryAccess().getAlternatives(), "rule__CorrelationCategory__Alternatives");
					put(grammarAccess.getPrimitiveTypesAccess().getAlternatives(), "rule__PrimitiveTypes__Alternatives");
					put(grammarAccess.getOperatorTypesAccess().getAlternatives(), "rule__OperatorTypes__Alternatives");
					put(grammarAccess.getAdviceCategoryAccess().getAlternatives(), "rule__AdviceCategory__Alternatives");
					put(grammarAccess.getIntertypeCategoryAccess().getAlternatives(), "rule__IntertypeCategory__Alternatives");
					put(grammarAccess.getIsFeatureTypesAccess().getAlternatives(), "rule__IsFeatureTypes__Alternatives");
					put(grammarAccess.getAspect_Oriented_ModelAccess().getGroup(), "rule__Aspect_Oriented_Model__Group__0");
					put(grammarAccess.getAspect_Oriented_ModelAccess().getGroup_5(), "rule__Aspect_Oriented_Model__Group_5__0");
					put(grammarAccess.getGoal_Model_ImplAccess().getGroup(), "rule__Goal_Model_Impl__Group__0");
					put(grammarAccess.getGoal_Model_ImplAccess().getGroup_4(), "rule__Goal_Model_Impl__Group_4__0");
					put(grammarAccess.getGoal_Model_ImplAccess().getGroup_4_3(), "rule__Goal_Model_Impl__Group_4_3__0");
					put(grammarAccess.getGoal_Model_ImplAccess().getGroup_5(), "rule__Goal_Model_Impl__Group_5__0");
					put(grammarAccess.getGoal_Model_ImplAccess().getGroup_5_3(), "rule__Goal_Model_Impl__Group_5_3__0");
					put(grammarAccess.getGoal_Model_ImplAccess().getGroup_6(), "rule__Goal_Model_Impl__Group_6__0");
					put(grammarAccess.getGoal_Model_ImplAccess().getGroup_6_3(), "rule__Goal_Model_Impl__Group_6_3__0");
					put(grammarAccess.getElementAccess().getGroup(), "rule__Element__Group__0");
					put(grammarAccess.getElementAccess().getGroup_5(), "rule__Element__Group_5__0");
					put(grammarAccess.getElementAccess().getGroup_5_3(), "rule__Element__Group_5_3__0");
					put(grammarAccess.getElementAccess().getGroup_6(), "rule__Element__Group_6__0");
					put(grammarAccess.getElementAccess().getGroup_6_3(), "rule__Element__Group_6_3__0");
					put(grammarAccess.getElementAccess().getGroup_7(), "rule__Element__Group_7__0");
					put(grammarAccess.getElementAccess().getGroup_7_3(), "rule__Element__Group_7_3__0");
					put(grammarAccess.getContributionAccess().getGroup(), "rule__Contribution__Group__0");
					put(grammarAccess.getContributionAccess().getGroup_4(), "rule__Contribution__Group_4__0");
					put(grammarAccess.getContributionAccess().getGroup_5(), "rule__Contribution__Group_5__0");
					put(grammarAccess.getCorrelationAccess().getGroup(), "rule__Correlation__Group__0");
					put(grammarAccess.getCorrelationAccess().getGroup_4(), "rule__Correlation__Group_4__0");
					put(grammarAccess.getCorrelationAccess().getGroup_5(), "rule__Correlation__Group_5__0");
					put(grammarAccess.getCrosscuttingAccess().getGroup(), "rule__Crosscutting__Group__0");
					put(grammarAccess.getCrosscuttingAccess().getGroup_2(), "rule__Crosscutting__Group_2__0");
					put(grammarAccess.getCrosscuttingAccess().getGroup_3(), "rule__Crosscutting__Group_3__0");
					put(grammarAccess.getCrosscuttingAccess().getGroup_7(), "rule__Crosscutting__Group_7__0");
					put(grammarAccess.getCrosscuttingAccess().getGroup_9(), "rule__Crosscutting__Group_9__0");
					put(grammarAccess.getCrosscuttingAccess().getGroup_9_3(), "rule__Crosscutting__Group_9_3__0");
					put(grammarAccess.getCrosscuttingAccess().getGroup_10(), "rule__Crosscutting__Group_10__0");
					put(grammarAccess.getCrosscuttingAccess().getGroup_10_3(), "rule__Crosscutting__Group_10_3__0");
					put(grammarAccess.getPointcutAccess().getGroup(), "rule__Pointcut__Group__0");
					put(grammarAccess.getPointcutAccess().getGroup_6(), "rule__Pointcut__Group_6__0");
					put(grammarAccess.getAdviceAccess().getGroup(), "rule__Advice__Group__0");
					put(grammarAccess.getAdviceAccess().getGroup_4(), "rule__Advice__Group_4__0");
					put(grammarAccess.getAdviceAccess().getGroup_4_3(), "rule__Advice__Group_4_3__0");
					put(grammarAccess.getAdviceAccess().getGroup_8(), "rule__Advice__Group_8__0");
					put(grammarAccess.getIntertypeDeclarationAccess().getGroup(), "rule__IntertypeDeclaration__Group__0");
					put(grammarAccess.getIntertypeDeclarationAccess().getGroup_7(), "rule__IntertypeDeclaration__Group_7__0");
					put(grammarAccess.getIntertypeDeclarationAccess().getGroup_9(), "rule__IntertypeDeclaration__Group_9__0");
					put(grammarAccess.getIntertypeDeclarationAccess().getGroup_9_3(), "rule__IntertypeDeclaration__Group_9_3__0");
					put(grammarAccess.getIntertypeDeclarationAccess().getGroup_10(), "rule__IntertypeDeclaration__Group_10__0");
					put(grammarAccess.getIntertypeDeclarationAccess().getGroup_10_3(), "rule__IntertypeDeclaration__Group_10_3__0");
					put(grammarAccess.getOperandAccess().getGroup(), "rule__Operand__Group__0");
					put(grammarAccess.getOperandAccess().getGroup_6(), "rule__Operand__Group_6__0");
					put(grammarAccess.getOperatorAccess().getGroup(), "rule__Operator__Group__0");
					put(grammarAccess.getAttributeAccess().getGroup(), "rule__Attribute__Group__0");
					put(grammarAccess.getIsFeatureAccess().getGroup(), "rule__IsFeature__Group__0");
					put(grammarAccess.getCardinalityAccess().getGroup(), "rule__Cardinality__Group__0");
					put(grammarAccess.getCardinalityAccess().getGroup_6(), "rule__Cardinality__Group_6__0");
					put(grammarAccess.getCardinalityAccess().getGroup_7(), "rule__Cardinality__Group_7__0");
					put(grammarAccess.getGroupFeatureAccess().getGroup(), "rule__GroupFeature__Group__0");
					put(grammarAccess.getGroupFeatureAccess().getGroup_9(), "rule__GroupFeature__Group_9__0");
					put(grammarAccess.getGroupFeatureAccess().getGroup_11(), "rule__GroupFeature__Group_11__0");
					put(grammarAccess.getGeneric_PropertyAccess().getGroup(), "rule__Generic_Property__Group__0");
					put(grammarAccess.getAspect_Oriented_ModelAccess().getGoalmodelAssignment_4(), "rule__Aspect_Oriented_Model__GoalmodelAssignment_4");
					put(grammarAccess.getAspect_Oriented_ModelAccess().getGoalmodelAssignment_5_1(), "rule__Aspect_Oriented_Model__GoalmodelAssignment_5_1");
					put(grammarAccess.getGoal_Model_ImplAccess().getNameAssignment_2(), "rule__Goal_Model_Impl__NameAssignment_2");
					put(grammarAccess.getGoal_Model_ImplAccess().getElementAssignment_4_2(), "rule__Goal_Model_Impl__ElementAssignment_4_2");
					put(grammarAccess.getGoal_Model_ImplAccess().getElementAssignment_4_3_1(), "rule__Goal_Model_Impl__ElementAssignment_4_3_1");
					put(grammarAccess.getGoal_Model_ImplAccess().getRelationshipAssignment_5_2(), "rule__Goal_Model_Impl__RelationshipAssignment_5_2");
					put(grammarAccess.getGoal_Model_ImplAccess().getRelationshipAssignment_5_3_1(), "rule__Goal_Model_Impl__RelationshipAssignment_5_3_1");
					put(grammarAccess.getGoal_Model_ImplAccess().getPropertyAssignment_6_2(), "rule__Goal_Model_Impl__PropertyAssignment_6_2");
					put(grammarAccess.getGoal_Model_ImplAccess().getPropertyAssignment_6_3_1(), "rule__Goal_Model_Impl__PropertyAssignment_6_3_1");
					put(grammarAccess.getElementAccess().getNameAssignment_1(), "rule__Element__NameAssignment_1");
					put(grammarAccess.getElementAccess().getTypeAssignment_4(), "rule__Element__TypeAssignment_4");
					put(grammarAccess.getElementAccess().getElementAssignment_5_2(), "rule__Element__ElementAssignment_5_2");
					put(grammarAccess.getElementAccess().getElementAssignment_5_3_1(), "rule__Element__ElementAssignment_5_3_1");
					put(grammarAccess.getElementAccess().getRelationshipAssignment_6_2(), "rule__Element__RelationshipAssignment_6_2");
					put(grammarAccess.getElementAccess().getRelationshipAssignment_6_3_1(), "rule__Element__RelationshipAssignment_6_3_1");
					put(grammarAccess.getElementAccess().getPropertyAssignment_7_2(), "rule__Element__PropertyAssignment_7_2");
					put(grammarAccess.getElementAccess().getPropertyAssignment_7_3_1(), "rule__Element__PropertyAssignment_7_3_1");
					put(grammarAccess.getContributionAccess().getLabelAssignment_3(), "rule__Contribution__LabelAssignment_3");
					put(grammarAccess.getContributionAccess().getSourceAssignment_4_1(), "rule__Contribution__SourceAssignment_4_1");
					put(grammarAccess.getContributionAccess().getTargetAssignment_5_1(), "rule__Contribution__TargetAssignment_5_1");
					put(grammarAccess.getCorrelationAccess().getLabelAssignment_3(), "rule__Correlation__LabelAssignment_3");
					put(grammarAccess.getCorrelationAccess().getSourceAssignment_4_1(), "rule__Correlation__SourceAssignment_4_1");
					put(grammarAccess.getCorrelationAccess().getTargetAssignment_5_1(), "rule__Correlation__TargetAssignment_5_1");
					put(grammarAccess.getCrosscuttingAccess().getSourceAssignment_2_1(), "rule__Crosscutting__SourceAssignment_2_1");
					put(grammarAccess.getCrosscuttingAccess().getTargetAssignment_3_1(), "rule__Crosscutting__TargetAssignment_3_1");
					put(grammarAccess.getCrosscuttingAccess().getPointcutAssignment_6(), "rule__Crosscutting__PointcutAssignment_6");
					put(grammarAccess.getCrosscuttingAccess().getPointcutAssignment_7_1(), "rule__Crosscutting__PointcutAssignment_7_1");
					put(grammarAccess.getCrosscuttingAccess().getAdviceAssignment_9_2(), "rule__Crosscutting__AdviceAssignment_9_2");
					put(grammarAccess.getCrosscuttingAccess().getAdviceAssignment_9_3_1(), "rule__Crosscutting__AdviceAssignment_9_3_1");
					put(grammarAccess.getCrosscuttingAccess().getIntertypeAssignment_10_2(), "rule__Crosscutting__IntertypeAssignment_10_2");
					put(grammarAccess.getCrosscuttingAccess().getIntertypeAssignment_10_3_1(), "rule__Crosscutting__IntertypeAssignment_10_3_1");
					put(grammarAccess.getPointcutAccess().getNameAssignment_1(), "rule__Pointcut__NameAssignment_1");
					put(grammarAccess.getPointcutAccess().getOperandAssignment_5(), "rule__Pointcut__OperandAssignment_5");
					put(grammarAccess.getPointcutAccess().getOperandAssignment_6_1(), "rule__Pointcut__OperandAssignment_6_1");
					put(grammarAccess.getAdviceAccess().getTypeAssignment_3(), "rule__Advice__TypeAssignment_3");
					put(grammarAccess.getAdviceAccess().getJoinpointAdviceAssignment_4_2(), "rule__Advice__JoinpointAdviceAssignment_4_2");
					put(grammarAccess.getAdviceAccess().getJoinpointAdviceAssignment_4_3_1(), "rule__Advice__JoinpointAdviceAssignment_4_3_1");
					put(grammarAccess.getAdviceAccess().getIdPointcutAssignment_7(), "rule__Advice__IdPointcutAssignment_7");
					put(grammarAccess.getAdviceAccess().getIdPointcutAssignment_8_1(), "rule__Advice__IdPointcutAssignment_8_1");
					put(grammarAccess.getIntertypeDeclarationAccess().getTypeAssignment_3(), "rule__IntertypeDeclaration__TypeAssignment_3");
					put(grammarAccess.getIntertypeDeclarationAccess().getIdPointcutAssignment_6(), "rule__IntertypeDeclaration__IdPointcutAssignment_6");
					put(grammarAccess.getIntertypeDeclarationAccess().getIdPointcutAssignment_7_1(), "rule__IntertypeDeclaration__IdPointcutAssignment_7_1");
					put(grammarAccess.getIntertypeDeclarationAccess().getNewElementAssignment_9_2(), "rule__IntertypeDeclaration__NewElementAssignment_9_2");
					put(grammarAccess.getIntertypeDeclarationAccess().getNewElementAssignment_9_3_1(), "rule__IntertypeDeclaration__NewElementAssignment_9_3_1");
					put(grammarAccess.getIntertypeDeclarationAccess().getNewAttributeAssignment_10_2(), "rule__IntertypeDeclaration__NewAttributeAssignment_10_2");
					put(grammarAccess.getIntertypeDeclarationAccess().getNewAttributeAssignment_10_3_1(), "rule__IntertypeDeclaration__NewAttributeAssignment_10_3_1");
					put(grammarAccess.getOperandAccess().getPrimitiveAssignment_3(), "rule__Operand__PrimitiveAssignment_3");
					put(grammarAccess.getOperandAccess().getJoinpointPointcutAssignment_5(), "rule__Operand__JoinpointPointcutAssignment_5");
					put(grammarAccess.getOperandAccess().getOperatorAssignment_6_1(), "rule__Operand__OperatorAssignment_6_1");
					put(grammarAccess.getOperatorAccess().getOperatorAssignment_3(), "rule__Operator__OperatorAssignment_3");
					put(grammarAccess.getAttributeAccess().getTypeAssignment_3(), "rule__Attribute__TypeAssignment_3");
					put(grammarAccess.getAttributeAccess().getValueAssignment_5(), "rule__Attribute__ValueAssignment_5");
					put(grammarAccess.getIsFeatureAccess().getLabelAssignment_3(), "rule__IsFeature__LabelAssignment_3");
					put(grammarAccess.getCardinalityAccess().getCardinalityMinAssignment_3(), "rule__Cardinality__CardinalityMinAssignment_3");
					put(grammarAccess.getCardinalityAccess().getCardinalityMaxAssignment_5(), "rule__Cardinality__CardinalityMaxAssignment_5");
					put(grammarAccess.getCardinalityAccess().getSourceAssignment_6_1(), "rule__Cardinality__SourceAssignment_6_1");
					put(grammarAccess.getCardinalityAccess().getTargetAssignment_7_1(), "rule__Cardinality__TargetAssignment_7_1");
					put(grammarAccess.getGroupFeatureAccess().getCardinalityGroupMinAssignment_3(), "rule__GroupFeature__CardinalityGroupMinAssignment_3");
					put(grammarAccess.getGroupFeatureAccess().getCardinalityGroupMaxAssignment_5(), "rule__GroupFeature__CardinalityGroupMaxAssignment_5");
					put(grammarAccess.getGroupFeatureAccess().getSourceAssignment_8(), "rule__GroupFeature__SourceAssignment_8");
					put(grammarAccess.getGroupFeatureAccess().getSourceAssignment_9_1(), "rule__GroupFeature__SourceAssignment_9_1");
					put(grammarAccess.getGroupFeatureAccess().getTargetAssignment_11_1(), "rule__GroupFeature__TargetAssignment_11_1");
					put(grammarAccess.getGeneric_PropertyAccess().getNameAssignment_1(), "rule__Generic_Property__NameAssignment_1");
					put(grammarAccess.getGeneric_PropertyAccess().getValueAssignment_4(), "rule__Generic_Property__ValueAssignment_4");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.xtext.plaovgraph.ui.contentassist.antlr.internal.InternalPLAOVgraphParser typedParser = (org.xtext.plaovgraph.ui.contentassist.antlr.internal.InternalPLAOVgraphParser) parser;
			typedParser.entryRuleAspect_Oriented_Model();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public PLAOVgraphGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(PLAOVgraphGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
