/*
 * generated by Xtext
 */
package org.xtext.plaovgraph;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PLAOVgraphRuntimeModule extends org.xtext.plaovgraph.AbstractPLAOVgraphRuntimeModule {

}
