/*
 * generated by Xtext
 */
package org.xtext.featuremodel;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class FeatureModelRuntimeModule extends org.xtext.featuremodel.AbstractFeatureModelRuntimeModule {

}
