/*
 * generated by Xtext
 */
package org.xtext.plaovgraph.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PLAOVgraphUiModule extends org.xtext.plaovgraph.ui.AbstractPLAOVgraphUiModule {
	public PLAOVgraphUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
