/*
* generated by Xtext
*/
package org.xtext.plaovgraph.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class PLAOVgraphAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/xtext/plaovgraph/parser/antlr/internal/InternalPLAOVgraph.tokens");
	}
}
