/*
* generated by Xtext
*/
package org.xtext.plaovgraph.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.plaovgraph.services.PLAOVgraphGrammarAccess;

public class PLAOVgraphParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private PLAOVgraphGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.plaovgraph.parser.antlr.internal.InternalPLAOVgraphParser createParser(XtextTokenStream stream) {
		return new org.xtext.plaovgraph.parser.antlr.internal.InternalPLAOVgraphParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Aspect_Oriented_Model";
	}
	
	public PLAOVgraphGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(PLAOVgraphGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
