/*
* generated by Xtext
*/
package org.xtext.plaovgraph.ui.contentassist;

import org.xtext.plaovgraph.ui.contentassist.AbstractPLAOVgraphProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class PLAOVgraphProposalProvider extends AbstractPLAOVgraphProposalProvider {

}
